version:            '3'

services:
  server-gitlab:
    # build:
    #   context:      './../../docker/server-gitlab-ce'
    #   dockerfile:   'Dockerfile'
    container_name: '${ENV_SERVICES_SERVER_GITLAB_CE_CONTAINER_NAME}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${ENV_SERVICES_DEFAULT_URL}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${ENV_SERVICES_SERVER_GITLAB_CE_PORTS_22}
        gitlab_rails['gitlab_email_from'] = '${GITLAB_RAILS_GITLAB_EMAIL_FROM}'
        gitlab_rails['gitlab_email_display_name'] = '${GITLAB_RAILS_GITLAB_EMAIL_DISPLAY_NAME}'
        gitlab_rails['gitlab_email_reply_to'] = '${GITLAB_RAILS_GITLAB_EMAIL_REPLY_TO}'
        gitlab_rails['smtp_enable'] = ${GITLAB_RAILS_SMTP_ENABLE}
        gitlab_rails['smtp_address'] = "${GITLAB_RAILS_SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = ${GITLAB_RAILS_SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${GITLAB_RAILS_SMTP_USER_NAME}"
        gitlab_rails['smtp_password'] = "${GITLAB_RAILS_SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${GITLAB_RAILS_SMTP_DOMAIN}"
        gitlab_rails['smtp_authentication'] = "${GITLAB_RAILS_SMTP_AUTHENTICATION}"
        gitlab_rails['smtp_enable_starttls_auto'] = ${GITLAB_RAILS_SMTP_ENABLE_STARTTLS_AUTO}
        nginx['client_max_body_size'] = '${NGINX_CLIENT_MAX_BODY_SIZE}'
    image:          'talsenteam/docker-gitlab-ce:${ENV_SERVICES_SERVER_GITLAB_CE_IMAGE_TAG}'
    hostname:       '${ENV_SERVICES_SERVER_GITLAB_CE_HOSTNAME}'
    ports:
      -             '${ENV_SERVICES_SERVER_GITLAB_CE_PORTS_22}:22'
      -             '${ENV_SERVICES_SERVER_GITLAB_CE_PORTS_80}:80'
    restart:        '${ENV_SERVICES_SERVER_GITLAB_CE_RESTART}'
    volumes:
      -             '${ENV_SERVICES_SERVER_GITLAB_CE_VOLUMES_ROOT}/etc/gitlab:/etc/gitlab'
      -             '${ENV_SERVICES_SERVER_GITLAB_CE_VOLUMES_ROOT}/var/log/gitlab:/var/log/gitlab'
      -             '${ENV_SERVICES_SERVER_GITLAB_CE_VOLUMES_ROOT}/var/opt/gitlab:/var/opt/gitlab'