version:            '3'

services:
  server-gitlab:
    # build:
    #   context:      './../../docker/server-gitlab-ce'
    #   dockerfile:   'Dockerfile'
    container_name: '${ENV_SERVICES_SERVER_GITLAB_CE_CONTAINER_NAME}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        nginx['client_max_body_size'] = '250M'
    image:          'talsenteam/docker-gitlab-ce:${ENV_SERVICES_SERVER_GITLAB_CE_IMAGE_TAG}'
    hostname:       '${ENV_SERVICES_SERVER_GITLAB_CE_HOSTNAME}'
    ports:
      -             '${ENV_SERVICES_SERVER_GITLAB_CE_PORTS_22}:22'
      -             '${ENV_SERVICES_SERVER_GITLAB_CE_PORTS_80}:80'
    restart:        '${ENV_SERVICES_SERVER_GITLAB_CE_RESTART}'
    volumes:
      -             '${ENV_SERVICES_DEFAULT_VOLUMES_ROOT}/etc/gitlab:/etc/gitlab'
      -             '${ENV_SERVICES_DEFAULT_VOLUMES_ROOT}/var/log/gitlab:/var/log/gitlab'
      -             '${ENV_SERVICES_DEFAULT_VOLUMES_ROOT}/var/opt/gitlab:/var/opt/gitlab'