version:            '3'

services:
  server-gitlab-ce:
    # build:
    #   context:      './../../docker/server-gitlab-ce'
    #   dockerfile:   'Dockerfile'
    container_name: 'server-gitlab-ce'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        nginx['client_max_body_size'] = '250M'
    image:          'talsenteam/docker-gitlab-ce:v11.2.5-ce.0'
    hostname:       'localhost'
    ports:
      -             '22:22'
      -             '80:80'
    restart:        'no'
    volumes:
      -             '${ENV_PATH_VOLUMES_ROOT}/server-gitlab-ce/etc/gitlab:/etc/gitlab'
      -             '${ENV_PATH_VOLUMES_ROOT}/server-gitlab-ce/var/log/gitlab:/var/log/gitlab'
      -             '${ENV_PATH_VOLUMES_ROOT}/server-gitlab-ce/var/opt/gitlab:/var/opt/gitlab'