version:            '3'

services:
  server-gitlab-ce:
    build:
      context:      './../../docker/server-gitlab-ce'
      dockerfile:   'Dockerfile'
    container_name: 'server-gitlab-ce'
    deploy:
      resources:
        limits:
          memory:     '12G'
        reservations:
          memory:     '4G'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        nginx['client_max_body_size'] = '250M'
        registry_external_url 'http://localhost:30250'
        registry_nginx['enable'] = true
    image:          'talsenteam/docker-gitlab-ce:v13.7.1-ce.0'
    hostname:       'server-gitlab-ce'
    ports:
      -             '30022:22'
      -             '80:80'
      -             '30250:30250'
    restart:        'no'
    volumes:
      -             '${ENV_PATH_VOLUMES_ROOT}/server-gitlab-ce/etc/gitlab:/etc/gitlab'
      -             '${ENV_PATH_VOLUMES_ROOT}/server-gitlab-ce/var/log/gitlab:/var/log/gitlab'
      -             '${ENV_PATH_VOLUMES_ROOT}/server-gitlab-ce/var/opt/gitlab:/var/opt/gitlab'
